/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/agpl.html>
 * 
 * Copyright (C) Ushahidi Inc. All Rights Reserved.
 */
package com.ushahidi.swiftriver.core.api.dao.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

/**
 * Base DAO implementation class for all DAO implementations
 * @author ekala
 *
 * @param <T>
 * @param <ID>
 */
public abstract class AbstractJpaDao {
	
	@PersistenceContext
	protected EntityManager em;

	public EntityManager getEm() {
		return em;
	}

	public void setEm(EntityManager em) {
		this.em = em;
	}
	
	/**
	 * Reserves a block of ids of size <code>increment</code> for the
	 * sequence in <code>sequenceName</code> and returns the first id
	 * in the reserved block.
	 * 
	 * This is a helper method for generating unique IDs for entities whose
	 * primary key is not automatically generated by the database
	 *  
	 * @param sequenceName
	 * @param increment
	 * @return
	 */
	public long getSequenceNumber(String sequenceName, int increment) {
		String sql = "SELECT NEXTVAL(:sequenceName, :increment)";
		
		Query query = em.createNativeQuery(sql);
		query.setParameter("sequenceName", sequenceName);
		query.setParameter("increment", increment);
		
		Integer epochSequenceNo = (Integer) query.getSingleResult();
		
		return Long.parseLong(epochSequenceNo.toString());
	}
		 
}
